### ISSUE TITLE
[feat] 내 체험 예약현황의 예약 정보 확인 및 처리 모달 UI

### ISSUE THREAD

**Issue by rosedaily** [GlobalNomad-FE/FE#131]
## Description
내 체험 예약현황의 예약 정보 확인 및 처리 모달 UI작업

## Todo
- [ ] 모달 팝업 및 탭이동등의 기능을 포함한 UI
- [ ] 신청 탭 목업 데이터 연결
- [ ] 신청 탭 내의 데이터 승인 및 거절
- [ ] 승인 탭 목업 데이터 연결
- [ ] 거절 탭 목업 데이터 연결

## ETC

![Image](https://github.com/GlobalNomad-FE/FE/assets/101369040/f6a0be19-5279-4466-aaaa-4ecdb9295f69)

![Image](https://github.com/GlobalNomad-FE/FE/assets/101369040/194eff3c-8c29-4613-8dea-bf1fd032dc9f)
