### ISSUE TITLE
[feat] 알림 모달 생성

### ISSUE THREAD

**Issue by gaem-gaem** [GlobalNomad-FE/FE#134]
## Description
알림 모달 생성 작업

## Todo
- [ ] 알림 종류는 예약 승인, 예약 거절로 무한 스크롤 | 최신순으로 정렬됩니다.
- [ ] '알림' 버튼을 누르면 알림 내역이 나타납니다.
- [ ] '읽음' 버튼을 누르면 해당 알림은 삭제가 됩니다.

## ETC
기타 사항
