### ISSUE TITLE
[feat] selectBox 컴포넌트 생성

### ISSUE THREAD

**Issue by rosedaily** [GlobalNomad-FE/FE#14]
## Description
select Box컴포넌트 생성

## Todo
- [x] select Box컴포넌트 UI
- [x] 카테고리 리스트 보여주기
- [x] 카테고리 리스트 선택 완료시 해당 카테고리가 보이도록 반영

## ETC
기타 사항
