### ISSUE TITLE
[feat] 메인페이지 리뷰반영 수정

### ISSUE THREAD

**Issue by seungcar** [GlobalNomad-FE/FE#151]
## Description
메인페이지 리뷰반영 수정

## Todo
- [x] 태블릿, 모바일 이미지 가로 자동 조절
- [x] 핫액티비티 태블릿,모바일 화면에서 드래그로 옆으로 넘길수있게
- [x] 카테고리 태블릿, 모바일 화면에서 드래그로 옆으로 넘길수있게

## ETC
기타 사항
