### ISSUE TITLE
[feat] 모달페이지 실제 데이터 연결

### ISSUE THREAD

**Issue by rosedaily** [GlobalNomad-FE/FE#154]
## Description
모달 페이지에 실제 데이터를 연결

## Todo
- [x] 신청 내역 탭 데이터 연결
- [x] 신청내역을 승인 및 거절 하도록 연결
- [x] 승인 내역 탭 데이터 연결
- [x] 거절 내역 탭 데이터 연결

## ETC
기타 사항
