### ISSUE TITLE
[feat] 예약 내역 모달 내 탭 및 셀렉트박스 동작 수정

### ISSUE THREAD

**Issue by rosedaily** [GlobalNomad-FE/FE#164]
## Description
모달 내에서 탭이나 셀렉트박스 선택 시 해당 항목이 초기화 되도록 수정 예정

## Todo
- [x] 모달을 닫으면 selectBox 초기화
- [x] 모달을 닫으면 예약 내역 항목 초기화
- [x] 모달 진입 시 예약 날짜의 첫번째 항목을 선택하고, 그 선택에 따라 예약 내역이 보여지도록
- [x] 승인 및 거절 진행 성공 시 승인, 거절 탭 카운팅과 예약내역을 다시 불러오도록

## ETC
기타 사항
