### ISSUE TITLE
[feat] 수정해야 하는 문제들

### ISSUE THREAD

**Issue by SeungAAA** [GlobalNomad-FE/FE#166]
## Description
자잘자잘하게 문제 있는 것들 고치는 브랜치입니다.

## Todo
- [ ] 로그인 전까지 페이지 둘러보는거 방지
- [x] 새로고침 하면 프로필 새로 불러오는것도 고치기
- [x] 로그인 로그아웃 페이지 반응형

## ETC
기타 사항
