### ISSUE TITLE
[feat] 예약 현황 내 잔여작업

### ISSUE THREAD

**Issue by rosedaily** [GlobalNomad-FE/FE#174]
## Description
예약 현황 내 잔여작업 

## Todo
- [x] 모바일 버전에서 팝업 사이즈 조절
- [x] 날짜 선택 시 날짜 크기 일정하게 변경
- [x] 태블릿 사이즈의 경우 셀렉트박스가 캘린더보다 긴 부분 수정
- [x] 데이터 미존재시 예약 내역 api를 호출하지 않도록 수정

## ETC
기타 사항
