### ISSUE TITLE
[feat] ModalBox 컴포넌트 생성

### ISSUE THREAD

**Issue by seungcar** [GlobalNomad-FE/FE#18]
## Description
모달 틀 생성

## Todo
- [x] zunstand 설치 & 설정
- [x] 모달 박스만들고 공통 ui까지
- [x] 모달 테스트 페이지 (임시용) 만들기

## ETC
기타 사항
