### ISSUE TITLE
[feat] 체험수정 페이지 수정

### ISSUE THREAD

**Issue by janyongs** [GlobalNomad-FE/FE#189]
## Description
체험수정 페이지 수정

## Todo
- [x] 버튼 글귀 수정
- [x] 닫기 버튼 크기 수정
- [x] 밑에 배경색 잘리는거 수정

## ETC
기타 사항
