### ISSUE TITLE
[style] 테일윈드 코드 대규모 변경

### ISSUE THREAD

**Issue by seungcar** [GlobalNomad-FE/FE#41]
## Description
테일윈드 코드 대규모 변경

## Todo
- [x] rem 디폴트값으로 되돌리기
- [x] 대괄호로 설정했던 숫자값 테일윈드 값으로 변경
- [x] 버튼들 전부 버튼 공통컴포넌트 사용하는것으로 변경
- [x] 반응형 사이즈 구현하기

## ETC
기타 사항
