### ISSUE TITLE
[feat] 버튼2개 팝업 공통컴포넌트로 변경

### ISSUE THREAD

**Issue by seungcar** [GlobalNomad-FE/FE#86]
## Description
버튼2개 팝업 공통컴포넌트로 변경

## Todo
- [ ] 버튼 이름 props로 받기
- [ ] 클릭하는 함수 props로 받기
- [ ] 팝업 닫히고 열리는거 상위컴포넌트에서 주고받는 형태로 변경

## ETC
기타 사항
